apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.233.46.173
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-hdd
  namespace: mailu-mailserver
  annotations:
    volume.beta.kubernetes.io/storage-class: "csi-gce-pd"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mail-storage
  namespace: mailu-mailserver
  annotations:
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
