apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jenkins-io-tls
spec:
  secretName: jenkins-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: build.safesecs.io
  dnsNames:
  - build.safesecs.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - build.safesecs.io
