apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: safesecs-io-tls
spec:
  secretName: safesecs-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: safesecs.io
  dnsNames:
  - safesecs.io
  - git.safesecs.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - safesecs.io
      - git.safesecs.io
