apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: mastodon-cert
spec:
  secretName: mastodon-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: focalmedia.io
  dnsNames:
  - focalmedia.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - focalmedia.io
