apiVersion: v1
kind: Service
metadata:
  name: mastodon-streaming
  namespace: mastodon
spec:
  type: NodePort
  ports:
    - name: streaming
      port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app: mastodon-streaming