kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitea
  namespace: gitea
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
