apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: seattlectf-httpproxy
spec:
  virtualhost:
    fqdn: seattlectf.com
    tls:
      secretName: seattlectf-tls
  routes:
    - conditions:
      - prefix: /
      services:
        - name: nginx-svc
          port: 80
