apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: seattlectf-tls
spec:
  secretName: seattlectf-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: seattlectf.com
  dnsNames:
  - seattlectf.com
