apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    fastcgi_cache_path /var/run/nginx/nginx-cache levels=1:2 keys_zone=WORDPRESS:100m inactive=60m;
    fastcgi_cache_key "$scheme$request_method$host$request_uri";
          
    server {
    listen 443 default_server;

    access_log /var/log/nginx/alphawolf.com.access.log;
    error_log /var/log/nginx/alphawolf.com.error.log;

    set $skip_cache 0;

    if ($request_method = POST) {
        set $skip_cache 1;
    }

    if ($query_string != "") {
        set $skip_cache 1;
    }

    if ($request_uri ~* "/wp-admin/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml") {
        set $skip_cache 1;
    }

    if ($http_cookie ~* "comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in") {
        set $skip_cache 1;
    }

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomain";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    add_header X-UA-Compatible "IE=edge";

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded_Proto $scheme;
    proxy_read_timeout 900;
    proxy_buffering on;

    gzip on;
    gzip_types text/plain application/xml text/css text/javascript image/svg+xml image/x-icon application/javascript application/x-javascript
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.(?!.*SV1)";
    gzip_proxied no-cache no-store private expired auth;
    gunzip on;

    root /var/www/html;
    index index.php;
    server_name alphawolfbeard.com www.alphawolfbeard.com;
    
    client_max_body_size 32M;
    proxy_ignore_client_abort on;
    fastcgi_ignore_client_abort on;
    keepalive_timeout 650;
    keepalive_requests 10000;
    
    location = /favicon.ico {
            log_not_found off;
            access_log off;
    }

    location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
    }

    location / {
            try_files $uri $uri/ /index.php?$args;
    }

    
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        try_files $uri /index.php;
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_pass unix:/var/run/nginx/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 600s;
        fastcgi_cache_bypass $skip_cache;
        fastcgi_cache WORDPRESS;
        fastcgi_cache_valid 60m;
    }

    location ~* ^.+.(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|rss|atom|js|css|png|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
            expires max;
            log_not_found off;
            access_log off;
    }

    location ~ /. {
        access_log off;
        log_not_found off;
    }

    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zz-docker
data:
  zz-docker.conf: |
    [global]
    daemonize = no
    
    [www]
    clear_env = no
