apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: ssd-save
  resources:
    requests:
      storage: 20Gi                
