kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: matomo-config-pvc
  namespace: matomo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
