apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.org/client-max-body-size: "10m"
spec:
  rules:
  - host:  
    http:
      paths:
      - backend:
          serviceName: 
          servicePort: 
  tls:
  - hosts:
    - 
    secretName: 
