kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-persistence-volume-claim-mongo
spec:
  storageClassName: csi-gce-pd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
