apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: 
spec:
  secretName: 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 
  dnsNames:
  - 
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - 
